/**
 * Copyright (c) Lucian Wischik
 */

/**
 * Runs before `tsc` as part of `npm run build`. config.ts is gitignored (see config.example.ts),
 * so a fresh clone (e.g. Vercel's build) won't have it. This script writes it from environment
 * variables CLIENT_ID and GOOGLE_MAPS_KEY in that case.
 *
 * If config.ts already exists (the normal case for local dev, where a developer created it by
 * hand from config.example.ts), this script leaves it untouched: we never want a build to clobber
 * a developer's local file, and local dev has no reason to set those environment variables.
 */
const fs = require('fs');
const path = require('path');

const CONFIG_PATH = path.join(__dirname, '..', 'config.ts');

if (fs.existsSync(CONFIG_PATH)) {
    process.exit(0);
}

const { CLIENT_ID, GOOGLE_MAPS_KEY } = process.env;
if (!CLIENT_ID || !GOOGLE_MAPS_KEY) {
    console.error(
        'config.ts is missing, and the CLIENT_ID / GOOGLE_MAPS_KEY environment variables are not ' +
        'both set to generate it. For local dev, copy config.example.ts to config.ts and fill in ' +
        'your own values. For Vercel, set CLIENT_ID and GOOGLE_MAPS_KEY in Project Settings > ' +
        'Environment Variables.'
    );
    process.exit(1);
}

fs.writeFileSync(
    CONFIG_PATH,
    `/**\n` +
    ` * Copyright (c) Lucian Wischik\n` +
    ` */\n\n` +
    `/**\n` +
    ` * Generated by scripts/generate-config.js from environment variables. Do not edit directly.\n` +
    ` */\n` +
    `export const CLIENT_ID = ${JSON.stringify(CLIENT_ID)};\n` +
    `export const GOOGLE_MAPS_KEY = ${JSON.stringify(GOOGLE_MAPS_KEY)};\n`
);
